### ISSUE TITLE
Issue on page /cardinals.html

### ISSUE THREAD

**Issue by jveltri33** [28left/descriptive_set_theory#40]
- Missing a period after defining the successor cardinal
- After the definition of the successor cardinal, Cantor's Theorem and the Axiom of Choice are referenced to give the inequalities. But don't they follow directly from the definition? It might make more sense if the successor cardinal were defined as the minimum over all larger ordinals, like the way cardinality is defined. Then it can be noted that this is a set in the same way since the cardinality of the power set is an upper bound by Cantor's Theorem.
- The "All finite ordinals" part seems incomplete. Should it say that all finite ordinals are cardinals?
- It should say "This **gives** the aleph-sequence" (or some other verb)
- Just before Proposition 5, it should say "alephs whose index is a limit ordinal" (no s on "ordinal")
- Just before the Operations on Cardinals section, $=\geq$ should just be $\geq$
- In Hessenberg's Theorem, the kappa is not in TeX. I think this is the only instance of a lowercase Greek letter not being formatted correctly on the page, so try to replicate here whatever you're doing in the other places. (And after checking, it seems that nothing changed on the ordinals page, so maybe try to implement there whatever you're doing here since it's working.)
- At the start of the Cardinality of R section, it should be "addition and multiplication **are** trivial"
- In conclusion 2, there is an extra "function"
- It might be good to put (CH) in the header of the continuum hypothesis before using the abbreviation

**Comment by 28left** [comment]
Thanks - those should be fixed now.

Regarding the TeX display issue, the Ordinals page shows up OK for me. Can you reload/empty cache and check again?

**Comment by jveltri33** [comment]
**I tried emptying the cache and using a different browser, but I still see the same thing. There are some instances where Greek letters are formatted properly, such as here:**

<img width="765" alt="Image" src="https://github.com/user-attachments/assets/aa2f93f3-97b1-4594-ba93-1eaf41636a29" />




**But most instances are not, such as here:**

<img width="759" alt="Image" src="https://github.com/user-attachments/assets/011f370a-f0c2-4dd1-a93a-fcc150c233ae" />

<img width="742" alt="Image" src="https://github.com/user-attachments/assets/afba5fbc-8e84-4f75-8a4e-02a95f325394" />

<img width="767" alt="Image" src="https://github.com/user-attachments/assets/082746ce-c89a-4ece-880d-e08a6b454463" />

**Comment by 28left** [comment]
I think I finally found a workaround that works everywhere, but it involves editing some instances manually. I am afraid I will overlook some frequently, so whenever you another instance that is not formatted correctly, please let me know.
